# .gitlab-ci.yml -- to test some source code build scenarios
# Copyright (C) 2016  Olaf Meeuwissen
#
# License: GPL-3.0+

variables:
  REGISTRY_HUB: "registry.gitlab.com/sane-project/ci-envs"
  CONFIGURE_MINI: "--enable-silent-rules"
  CONFIGURE_FULL: "--with-usb --enable-avahi --enable-pnm-backend"

.build_template: &build_definition
  stage: build
  script:
  - ./configure $CONFIGURE_OPTS
  - make -j2 -k $MAKE_FLAGS

build:debian-8-mini:
  image: $REGISTRY_HUB:debian-8-mini
  variables:
    CONFIGURE_OPTS: "$CONFIGURE_MINI"
    MAKE_FLAGS: "CFLAGS=-Werror"
  <<: *build_definition

build:debian-8-full:
  image: $REGISTRY_HUB:debian-8-full
  variables:
    CONFIGURE_OPTS: "$CONFIGURE_MINI $CONFIGURE_FULL"
    MAKE_FLAGS: "CFLAGS=-Werror"
  <<: *build_definition

build:alpine-3.4-musl:
  image: $REGISTRY_HUB:alpine-3.4-musl
  variables:
    CONFIGURE_OPTS: "$CONFIGURE_MINI $CONFIGURE_FULL"
  <<: *build_definition

build:fedora-24-clang:
  image: $REGISTRY_HUB:fedora-24-clang
  variables:
    CONFIGURE_OPTS: "$CONFIGURE_MINI $CONFIGURE_FULL"
  <<: *build_definition
